//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_customer_address
    {
        public int id { get; set; }
        public long crm_employee_id { get; set; }
        public int crm_address_id { get; set; }
    
        public virtual crm_address crm_address { get; set; }
        public virtual crm_employee crm_employee { get; set; }
    }
}
