//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_dependent
    {
        public int id { get; set; }
        public long crm_customer_id { get; set; }
        public Nullable<int> crm_address_id { get; set; }
        public string name { get; set; }
    
        public virtual crm_address crm_address { get; set; }
        public virtual crm_customer crm_customer { get; set; }
    }
}
