//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_mortgage_daily_payables
    {
        public int id { get; set; }
        public long trans_transaction_header_id { get; set; }
        public long crm_customer_id { get; set; }
        public int user_id { get; set; }
        public int period { get; set; }
        public System.DateTime transaction_date { get; set; }
        public decimal amount_borrowed { get; set; }
        public decimal total_interest { get; set; }
        public decimal daily_amount_payables { get; set; }
        public System.DateTime date_started { get; set; }
        public System.DateTime date_ended { get; set; }
        public decimal daily_amount_interest { get; set; }
    
        public virtual crm_customer crm_customer { get; set; }
        public virtual crm_user crm_user { get; set; }
        public virtual trans_transaction_header trans_transaction_header { get; set; }
    }
}
