//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_job_position_tf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crm_job_position_tf()
        {
            this.crm_assignment = new HashSet<crm_assignment>();
        }
    
        public int id { get; set; }
        public long crm_employee_id { get; set; }
        public int crm_job_position_mf_id { get; set; }
        public Nullable<System.DateTime> date_hired { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_assignment> crm_assignment { get; set; }
        public virtual crm_employee crm_employee { get; set; }
        public virtual crm_job_position_mf crm_job_position_mf { get; set; }
    }
}
