//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_seminar_scheduler_mf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crm_seminar_scheduler_mf()
        {
            this.crm_seminar_scheduler_tf = new HashSet<crm_seminar_scheduler_tf>();
        }
    
        public int id { get; set; }
        public System.DateTime scheduled_date { get; set; }
        public long crm_employee_id { get; set; }
        public int crm_user_id { get; set; }
        public string description { get; set; }
    
        public virtual crm_employee crm_employee { get; set; }
        public virtual crm_user crm_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_seminar_scheduler_tf> crm_seminar_scheduler_tf { get; set; }
    }
}
