//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_assignment
    {
        public int id { get; set; }
        public int crm_job_positon_tf_id { get; set; }
        public int crm_branch_id { get; set; }
        public long crm_employee_id { get; set; }
        public int mf_status_id { get; set; }
    
        public virtual crm_branch crm_branch { get; set; }
        public virtual crm_employee crm_employee { get; set; }
        public virtual crm_job_position_tf crm_job_position_tf { get; set; }
        public virtual mf_status mf_status { get; set; }
    }
}
