//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_seminar_scheduler_tf
    {
        public int id { get; set; }
        public int crm_seminar_scheduler_mf_id { get; set; }
        public long crm_customer_id { get; set; }
        public int mf_status_id { get; set; }
    
        public virtual crm_customer crm_customer { get; set; }
        public virtual crm_seminar_scheduler_mf crm_seminar_scheduler_mf { get; set; }
        public virtual mf_status mf_status { get; set; }
    }
}
