//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crm_user()
        {
            this.crm_mortgage_daily_payables = new HashSet<crm_mortgage_daily_payables>();
            this.crm_requirements_tf = new HashSet<crm_requirements_tf>();
            this.crm_seminar_scheduler_mf = new HashSet<crm_seminar_scheduler_mf>();
            this.trans_transaction_detail = new HashSet<trans_transaction_detail>();
            this.trans_transaction_detail1 = new HashSet<trans_transaction_detail>();
            this.trans_payment_collection = new HashSet<trans_payment_collection>();
            this.trans_payment_collection1 = new HashSet<trans_payment_collection>();
            this.trans_transaction_header = new HashSet<trans_transaction_header>();
            this.trans_transaction_header1 = new HashSet<trans_transaction_header>();
        }
    
        public int id { get; set; }
        public Nullable<long> crm_employee_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual crm_employee crm_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_mortgage_daily_payables> crm_mortgage_daily_payables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_requirements_tf> crm_requirements_tf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_seminar_scheduler_mf> crm_seminar_scheduler_mf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_transaction_detail> trans_transaction_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_transaction_detail> trans_transaction_detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_payment_collection> trans_payment_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_payment_collection> trans_payment_collection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_transaction_header> trans_transaction_header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_transaction_header> trans_transaction_header1 { get; set; }
    }
}
