//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_pricebook_detail
    {
        public int id { get; set; }
        public int pricebook_header_id { get; set; }
        public int item_id { get; set; }
        public int uom_id { get; set; }
        public int status_id { get; set; }
        public decimal price_vat_ex { get; set; }
        public decimal price_vat_in { get; set; }
        public string upc { get; set; }
        public string sku { get; set; }
    
        public virtual inv_item inv_item { get; set; }
        public virtual mf_status mf_status { get; set; }
        public virtual inv_pricebook_header inv_pricebook_header { get; set; }
        public virtual inv_uom inv_uom { get; set; }
    }
}
