//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mf_payment_terms
    {
        public int id { get; set; }
        public string description { get; set; }
        public int period { get; set; }
        public Nullable<decimal> rate { get; set; }
    }
}
