//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mortgageEntities : DbContext
    {
        public mortgageEntities()
            : base("name=mortgageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<crm_address> crm_address { get; set; }
        public virtual DbSet<crm_branch> crm_branch { get; set; }
        public virtual DbSet<crm_civil_status> crm_civil_status { get; set; }
        public virtual DbSet<crm_contact> crm_contact { get; set; }
        public virtual DbSet<crm_customer> crm_customer { get; set; }
        public virtual DbSet<crm_customer_address> crm_customer_address { get; set; }
        public virtual DbSet<crm_dependent> crm_dependent { get; set; }
        public virtual DbSet<crm_employee> crm_employee { get; set; }
        public virtual DbSet<crm_employee_address> crm_employee_address { get; set; }
        public virtual DbSet<crm_job_position_mf> crm_job_position_mf { get; set; }
        public virtual DbSet<crm_job_position_tf> crm_job_position_tf { get; set; }
        public virtual DbSet<crm_mortgage_daily_payables> crm_mortgage_daily_payables { get; set; }
        public virtual DbSet<crm_requirements_mf> crm_requirements_mf { get; set; }
        public virtual DbSet<crm_requirements_tf> crm_requirements_tf { get; set; }
        public virtual DbSet<crm_seminar_scheduler_mf> crm_seminar_scheduler_mf { get; set; }
        public virtual DbSet<crm_seminar_scheduler_tf> crm_seminar_scheduler_tf { get; set; }
        public virtual DbSet<crm_user> crm_user { get; set; }
        public virtual DbSet<inv_discount> inv_discount { get; set; }
        public virtual DbSet<inv_item_category> inv_item_category { get; set; }
        public virtual DbSet<inv_pricebook_detail> inv_pricebook_detail { get; set; }
        public virtual DbSet<inv_pricebook_header> inv_pricebook_header { get; set; }
        public virtual DbSet<inv_pricebook_type> inv_pricebook_type { get; set; }
        public virtual DbSet<inv_uom> inv_uom { get; set; }
        public virtual DbSet<mf_document_type> mf_document_type { get; set; }
        public virtual DbSet<mf_payment_terms> mf_payment_terms { get; set; }
        public virtual DbSet<mf_payment_type> mf_payment_type { get; set; }
        public virtual DbSet<mf_status> mf_status { get; set; }
        public virtual DbSet<mf_tax> mf_tax { get; set; }
        public virtual DbSet<trans_payment_collection> trans_payment_collection { get; set; }
        public virtual DbSet<trans_transaction_detail> trans_transaction_detail { get; set; }
        public virtual DbSet<trans_transaction_header> trans_transaction_header { get; set; }
        public virtual DbSet<trans_transaction_type> trans_transaction_type { get; set; }
        public virtual DbSet<crm_customer_contact> crm_customer_contact { get; set; }
        public virtual DbSet<crm_employee_contact> crm_employee_contact { get; set; }
        public virtual DbSet<crm_assignment> crm_assignment { get; set; }
        public virtual DbSet<inv_item> inv_item { get; set; }
    }
}
