//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_transaction_detail
    {
        public long id { get; set; }
        public long trans_transaction_header_id { get; set; }
        public Nullable<int> inv_item_id { get; set; }
        public Nullable<int> inv_uom_id { get; set; }
        public Nullable<int> mf_tax_id { get; set; }
        public Nullable<int> inv_discount_id { get; set; }
        public Nullable<int> crm_user_id { get; set; }
        public Nullable<int> crm_admin_id { get; set; }
        public Nullable<int> mf_status_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> inv_qty { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> price_wo_tax { get; set; }
        public Nullable<decimal> price_w_tax { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> line_discount_amount_applied { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> extended_total { get; set; }
        public string upc { get; set; }
        public string sku { get; set; }
        public string comment { get; set; }
    
        public virtual crm_user crm_user { get; set; }
        public virtual crm_user crm_user1 { get; set; }
        public virtual inv_discount inv_discount { get; set; }
        public virtual inv_item inv_item { get; set; }
        public virtual inv_uom inv_uom { get; set; }
        public virtual mf_status mf_status { get; set; }
        public virtual mf_tax mf_tax { get; set; }
        public virtual trans_transaction_header trans_transaction_header { get; set; }
    }
}
